[tool.poetry]
name = "trainscanner"
version = "0.19.1"
homepage = "https://github.com/vitroid/trainscanner"
description = ""
authors = ["vitroid <vitroid@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
TiledImage = "^0.1.1"
opencv-python-headless = "^4.10.0.84"
click = "^8.1.8"
tqdm = "^4.67.1"
pyqt5 = { version = "^5.15.11", markers = "sys_platform == 'darwin' and platform_machine == 'arm64' and platform_release < '20.0.0'" }
pyqt6 = { version = "^6.6.1", markers = "sys_platform == 'darwin' and platform_machine == 'arm64' and platform_release >= '20.0.0'" }

[tool.poetry.scripts]
trainscanner        = 'trainscanner.trainscanner_gui:main'
trainscanner_pass1  = 'trainscanner.pass1_gui:main'
trainscanner_stitch = 'trainscanner.stitch_gui:main'
trainscanner_shakereduction = 'trainscanner.shakereduction:main'
filmify             = 'trainscanner.converter.film:main'
rectify             = 'trainscanner.converter.rect:main'
helicify            = 'trainscanner.converter.helix:main'
hansify             = 'trainscanner.converter.hans_style:main'
ts_converter        = 'trainscanner.converter.gui:main'
movify              = 'trainscanner.converter.scroll:main'
movify2             = 'trainscanner.converter.movie2:main'

[tool.poetry.group.dev.dependencies]
jinja2 = "^3.1.6"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
