[tool.poetry]
name = "trainscanner"
version = "0.14.3"
homepage = "https://github.com/vitroid/trainscanner"
description = ""
authors = ["vitroid <vitroid@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
TiledImage = "^0.1.1"
PyQt6 = "^6.7.1"
opencv-python-headless = "^4.10.0.84"

[tool.poetry.scripts]
trainscanner        = 'trainscanner.trainscanner_gui:main'
trainscanner_pass1  = 'trainscanner.pass1_gui:main'
trainscanner_stitch = 'trainscanner.stitch_gui:main'
trainscanner_shakereduction = 'trainscanner.shakereduction:main'
filmify             = 'ts_conv.film:main'
rectify             = 'ts_conv.rect:main'
helicify            = 'ts_conv.helix:main'
hansify             = 'ts_conv.hans_style:main'
ts_converter        = 'ts_conv.converter_gui:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
