[tool.poetry]
name = "trainscanner"
version = "0.26.2"
homepage = "https://github.com/vitroid/trainscanner"
description = ""
authors = ["vitroid <vitroid@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
TiledImage = "^0.1.1"
opencv-python-headless = "^4.10.0.84"
tqdm = "^4.67.1"
pillow = "^11.2.1"
pyqt5 = "^5.15.11"

[tool.poetry.scripts]
trainscanner        = 'trainscanner.trainscanner_gui:main'
trainscanner_pass1  = 'trainscanner.pass1_gui:main'
trainscanner_stitch = 'trainscanner.stitch_gui:main'
antishake           = 'trainscanner.shake_reduction2_gui:main'
filmify             = 'trainscanner.converter.film:main'
rectify             = 'trainscanner.converter.rect:main'
helicify            = 'trainscanner.converter.helix:main'
ts_converter        = 'trainscanner.converter.gui:main'
movify              = 'trainscanner.converter.movie:main'

[tool.poetry.group.dev.dependencies]
jinja2 = "^3.1.6"
toml = "^0.10.2"
matplotlib = "^3.10.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
