{% set name = "trainscanner" %}
{% set version = "0.12.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "00153ddd7761462fd13e052a36059ef755b2055c42ec3d56348f73b806f25f08" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  # copied from https://pypi.python.org/pypi/TrainScanner
  url: https://files.pythonhosted.org/packages/0e/23/0e1f4faacfb1e761443f40c183efd36b9b4bd1a09e5fe6227dc73be9e4e1/TrainScanner-0.12.0.tar.gz
#https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - trainscanner        = trainscanner.trainscanner_gui:main
    - trainscanner_pass1  = trainscanner.pass1_gui:main
    - trainscanner_stitch = trainscanner.stitch_gui:main
    - trainscanner_shakereduction = trainscanner.shakereduction:main
    - filmify             = ts_conv.film:main
    - rectify             = ts_conv.rect:main
    - helicify            = ts_conv.helix:main
    - hansify             = ts_conv.hans_style:main
    - ts_converter        = ts_conv.converter_gui:main
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.5
    - setuptools
    - numpy
    - pyqt >=5
  run:
    - python >=3.5
    - numpy
    - pyqt >=5

test:
  imports:
    - trainscanner
    - ts_conv
  commands:
#    - trainscanner --help
#    - trainscanner_pass1 --help
#    - trainscanner_stitch --help
#    - trainscanner_shakereduction --help
#    - filmify --help
#    - rectify --help
#    - helicify --help
#    - hansify --help
#    - ts_converter --help

about:
  home: https://github.com/vitroid/TrainScanner/
  license: MIT
  license_family: MIT
  license_file: ''
  summary: Generate a long image strip from a train video
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''

app:
  entry: trainscanner .  [win]
  entry: trainscanner .  [linux]
  entry: trainscanner .  [osx]
  icon: trainscanner.png
  summary: TrainScanner app makes a long photo from the train video.

#  entry: trainscanner .
